version: "3.10"

services:
  db:
    image: postgis/postgis:15-master
    container_name: adonis_db
    ports:
      - "25432:5432"
    environment:
      - POSTGRES_DB=lucid
      - POSTGRES_USER=lucid
      - POSTGRES_PASSWORD=sfdsgdfgdfgd
    volumes:
      - pgdata:/var/lib/postgresql/data
      - pgsql-sock:/var/run/postgresql
    networks:
      - web

  backend:
    image: node:18.16.1
    container_name: adonis_backend
    ports:
      - "3333:3333"
    networks:
      - web
    depends_on:
      - db
    volumes:
      - ./:/backend
      - pgsql-sock:/var/run/postgresql
    working_dir: /backend
    command: bash -c "
      npm install &&
      npm run migration:run &&
      npm run dev
      "


volumes:
  pgdata:
  pgsql-sock:

networks:
  web: